name: Telegram Notification

on:
  push:
    branches: [ "main", "master" ]

jobs:
  telegram-status:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Новый пуш в репозиторий!
            👤 Автор: ${{ github.actor }}
            📝 Коммит: ${{ github.event.head_commit.message }}
